//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jeti_v0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JETIEntities : DbContext
    {
        public JETIEntities()
            : base("name=JETIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActiveContract> ActiveContracts { get; set; }
        public virtual DbSet<PriceCapture> PriceCaptures { get; set; }
        public virtual DbSet<SecurityMaster> SecurityMasters { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
