//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jeti_v0
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceCapture
    {
        public System.DateTime IBTimestamp { get; set; }
        public string Ticker { get; set; }
        public double Price { get; set; }
        public Nullable<double> Open_Price { get; set; }
        public Nullable<double> Close_Price { get; set; }
        public Nullable<double> Bid { get; set; }
        public Nullable<double> Ask { get; set; }
        public Nullable<double> Volume { get; set; }
    }
}
