//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jeti_v0
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityMaster
    {
        public int SecurityID { get; set; }
        public string SecType { get; set; }
        public string Exchange { get; set; }
        public string Currency { get; set; }
        public string IBFuturesLocalSymbol { get; set; }
        public string FuturesGenericSymbol { get; set; }
        public Nullable<int> FuturesYear { get; set; }
        public string FuturesYearCode { get; set; }
        public string FuturesMonth { get; set; }
        public string FuturesMonthCode { get; set; }
    }
}
